api-host: http://localhost:8080
client-host: http://localhost:5173

auth:
  github:
    client-id: test-a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5j0a1b2c3d4e5f6g7h8i9j0
    client-secret: test-a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5j0a1b2c3d4e5f6g7h8i9j0
    redirect-uri: ${api-host}/auth/social/callback/github
    client-uri: ${client-host}

security:
  jwt:
    secret-key: test-a1b2c3d4e5f6g7h8i9j0a1b2c3d4e5j0a1b2c3d4e5f6g7h8i9j0
    expiration-time: 86400000 # 1 day
