services:
  application:
    image: ${DOCKERHUB_REPO}
    environment:
        SPRING_PROFILES_ACTIVE: dev
        TZ: Asia/Seoul
    ports:
      - "8080:8080"
    restart: always
    container_name: sb-server
