name: Server CI

on:
  push:
    branches: ['main', 'dev']
    paths: ['server/**']
  pull_request:
    branches: ['main', 'dev']
    paths: ['server/**']

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: cd server && ./gradlew build
